apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-dep
  labels:
    app: whoami
spec:
  replicas: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
      matchLabels:
        app: whoami
  template:
    metadata:
      name: whoami
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-pod
        image: lewisohn/whoami:0.1.6
        ports:
          - containerPort: 5000
