jobs:
  - name: job-whoami
    public: true
    plan:
      - task: whoami
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: verifa/whoami}
          run:
            path: echo
            args: [test]
