resources:
- name: app-whoami
  type: git
  source:
    uri: https://github.com/lewisohn/whoami.git
    branch: master

- name: docker-hub
  type: docker-image
  source:
      repository: lewisohn/whoami

jobs:
  - name: job-whoami
    public: true
    plan:
    - get: app-whoami
      trigger: true
    - task: run-tests
      file: app-whoami/ci/run-tests.yaml
    - put: docker-hub
