resources:
- name: resource-whoami
  type: git
  source:
    uri: https://github.com/lewisohn/whoami.git
    branch: master
- name: timer-whoami
  type: time
  source:
    interval: 1m

jobs:
  - name: job-whoami
    public: true
    plan:
      - get: resource-whoami
        trigger: true
      - task: run-tests
        file: resource-whoami/ci/run-tests.yaml
